version: "3.9"

services:
  backend:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - static:/srv/app/static
      - media:/srv/app/media
    command: >
      sh -c "python manage.py wait_for_db &&
                  python manage.py migrate &&
                  python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env.dev
    depends_on:
      - db


  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    env_file:
      - .env.dev


volumes:
  dev-db-data:
  media:
  static:
