# Generated by Django 4.0.10 on 2024-10-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_amenities_price_booking_price_cottage_expenses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenities',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
