# Generated by Django 4.0.10 on 2024-10-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_amenities_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='cottage',
            name='base_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
