# Generated by Django 4.0.10 on 2024-11-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_cottage_base_expenses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cottage',
            name='base_capacity',
        ),
        migrations.RemoveField(
            model_name='cottage',
            name='base_expenses',
        ),
        migrations.AlterField(
            model_name='cottage',
            name='total_capacity',
            field=models.IntegerField(),
        ),
    ]
