# Generated by Django 4.0.10 on 2024-11-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_cottage_base_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cottage',
            name='user',
        ),
        migrations.AlterField(
            model_name='cottage',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='core.amenities'),
        ),
    ]
